<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.23" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\BotDetector.Business\BotDetector.Business.csproj" />
    <ProjectReference Include="..\BotDetector.Infrastructure\BotDetector.Infrastructure.csproj" />
    <ProjectReference Include="..\BotDetector.Common\BotDetector.Common.csproj" />
  </ItemGroup>
</Project>